version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=my_db_user
      - POSTGRES_PASSWORD=my_db_password
      - POSTGRES_DB=my_db_name
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=my_db_user
      - POSTGRES_PASSWORD=my_db_password
      - POSTGRES_DB=my_db_name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
