# Generated by Django 4.2 on 2023-04-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userrepositories_userprofile_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
