# Generated by Django 4.2 on 2023-04-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrepositories',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userrepositories',
            name='html_url',
        ),
        migrations.AddField(
            model_name='userrepositories',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userrepositories',
            name='owner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrepositories',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userrepositories',
            name='stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrepositories',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userrepositories',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
